# Generated by Django 5.0.3 on 2024-03-12 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_ID', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('admit_year', models.DateField(null=True)),
                ('passwd', models.CharField(max_length=100, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('pic', models.ImageField(null=True, upload_to='static/profie/')),
                ('role', models.CharField(db_default='student', default='Student', max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semester')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('teacher_Id', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=150, primary_key=True, serialize=False)),
                ('roles', models.CharField(max_length=100, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.department')),
            ],
        ),
    ]
