# Generated by Django 5.0.3 on 2024-03-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_subject_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='roles',
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.roles'),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.roles'),
        ),
    ]
