# Generated by Django 5.0.3 on 2024-03-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_teacher_roles_teacher_role_alter_student_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='passwd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/profie/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(db_default='Student', max_length=100, null=True),
        ),
    ]
