# Generated by Django 5.0.3 on 2024-03-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('mobile', models.IntegerField(max_length=12, null=True)),
                ('course', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
