# Generated by Django 5.0.3 on 2024-03-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='mysoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_title', models.CharField(max_length=100, null=True)),
                ('software_description', models.TextField(null=True)),
                ('software_picture', models.ImageField(null=True, upload_to='static/softwarepic/')),
                ('software_date', models.DateField()),
            ],
        ),
    ]
