# Generated by Django 5.0.3 on 2024-03-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_mysoftware'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysoftware',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
