# Generated by Django 5.0.3 on 2024-03-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_liveclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
