# Generated by Django 5.0.3 on 2024-04-12 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_liveclass_time_alter_liveclass_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.department'),
        ),
    ]
