# Generated by Django 5.0.3 on 2024-05-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_placement_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='placement',
        ),
    ]
