# Generated by Django 5.0.3 on 2024-05-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_delete_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_picture', models.ImageField(null=True, upload_to='static/placement')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.department')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.session')),
            ],
        ),
    ]
