# Generated by Django 5.0.3 on 2024-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_submittedtask_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedtask',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
