# Generated by Django 5.0.3 on 2024-06-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_delete_mylectures'),
    ]

    operations = [
        migrations.CreateModel(
            name='mylectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('semester', models.CharField(max_length=100, null=True)),
                ('vlink', models.CharField(max_length=300, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='static/video')),
                ('video_description', models.TextField(null=True)),
                ('added_date', models.DateField(null=True)),
            ],
        ),
    ]
