# Generated by Django 5.0.3 on 2024-06-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_mylectures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mylectures',
        ),
    ]
