# Generated by Django 5.0.3 on 2024-06-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_remove_mylectures_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='static/video'),
        ),
    ]
