# Generated by Django 5.0.3 on 2024-06-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_remove_enotes_note_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='enotes',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
