# Generated by Django 5.0.3 on 2024-06-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_enotes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enotes',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
