# Generated by Django 5.0.3 on 2024-06-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_alter_enotes_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enotes',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enotes',
            name='semester',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
